server:
  port: 8081
  

spring:  jpa:    show-sql: true
    hibernate:      ddl-auto: update
      naming:        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:      hibernate:
        format_sql: true 
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:    static-path-pattern: /resources/**
    throw-exception-if-no-handler-found: true
  web:    resources:      static-locations:        - classpath:/css/
        - classpath:/js/
  
      
com:
  example:
    admission:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/admissionman
        username: root
        password: root123